CREATE TABLE [dbo].[Scenario] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [Label]    NVARCHAR (30)  NULL,
    [Text]     NVARCHAR (250) NULL,
    [GameOver] TINYINT        NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[Choice] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [CurrentScenarioId] INT            NULL,
    [NextScenarioId]    INT            NOT NULL,
    [Text]              NVARCHAR (250) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Choice_NextScenario] FOREIGN KEY ([NextScenarioId]) REFERENCES [dbo].[Scenario] ([Id]),
    CONSTRAINT [FK_Choice_CurrentScenario] FOREIGN KEY ([CurrentScenarioId]) REFERENCES [dbo].[Scenario] ([Id])
);

SET IDENTITY_INSERT [dbo].[Scenario] ON
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (1, N'Début de l''aventure', N'Vous êtes devant la porte du donjon. Votre mission : capturer un mangemort dans le donjon, vous êtes muni de votre baguette et d''une dague pour accomplir cette tâche', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (2, N'Lâche', N'Game Over. L''aventure fut courte, mais au moins vous êtes en vie', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (3, N'Porte Boss', N'Vous entrez dans le donjon, une porte menaçante se trouve sur votre droite.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (4, N'Boss Surprise', N'Devant vous ce tien le mangemort que vous devez capturer. Cependant, il ne vous regarde pas encore, il pense sûrement que vous êtes un serviteur.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (5, N'Victoire Facile', N'Le mangemort est vaincu, mais à quel prix ? Vous êtes arrêté par le ministère de la magie et finirez vos jours en prison. ', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (6, N'Defaite Prison', N'Vous frappez le mangemort derrière la tête avec une flasque qui traînait. Le mangemort est immobilisé. Vous le capturez, vous avez accompli votre mission.', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (7, N'Intersection Départ', N'Vous arrivez à une intersection. Que faire ?', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (8, N'Trape à pique', N'Un piège était présent et vous êtes tombé en plein dedans RIP.', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (9, N'Porte Araignée', N'Vous vous trouvez devant une porte verrouillée.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (10, N'Araignée Géante', N'Vous entrez dans la salle une araignée géante fonce vers vous.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (11, N'Départ raté', N'L''araignée géante vous rattrape et vous dévore, vous êtes mort.', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (12, N'A l''attaque de l''araignée', N'Vous décidez de vous battre contre l''araignée, elle n''est pas si géante finalement, quel sort lancer pour vaincre l''araignée.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (13, N'Passage secret', N'En faisant demi-tour vous apercevez le long du couloir un escalier caché dans le noir', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (14, N'Elfe de Maison aggressif', N'Vous montez l''escalier. En haut de l''escalier une petite pièce éclairée, un elfe de maison est en train de travailler, il vous repère et vous fonce dessus.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (15, N'Victoire contre Araignée', N'L''araignée s''écroule à terre de douleur, vous l''achevez avec votre dague, c''était facile.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (16, N'Inefficace', N'Le sort n''a aucun effet vous êtes mort.', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (17, N'Victoire Difficile', N'Vous arrivez à battre l''araignée tant bien que mal, vous devriez sûrement vous reposez. ', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (18, N'Epuisement', N'Vous vous écroulez par terre, quand on vous dit de vous reposez ! Vous ne vous releverez plus jamais', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (19, N'Mort à la traitre', N'Vous vous prenez dix flèche dans le dos, vous entendez "ARRÊTEZ DE FAIRE DEMI-TOUR", sûrement le scénariste qui ne vous aime pas, vous êtes mort', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (20, N'Super Efficace', N'Comme tout le monde le sait les dagues sont super efficaces contre les elfes de maison. Vous observez la pièce autour de vous, une armoire, une table et un couloir pour continuer votre aventure', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (21, N'Desarmé', N'L''elfe vous saute dessus et vous enlève la baguette des mains.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (22, N'Chute', N'Dans la précipitation vous tombez dans les escaliers et mourrez de votre chute.', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (23, N'Carte', N'Vous trouvez une plan du donjon. Deux lieux attires votre attention la salle du maitre qui était la porte à l''entré et la salle des artefacts', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (24, N'Rien', N'Vous ne trouvez rien dans l''armoire à première vue', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (25, N'Intersection Etage', N'Vous arrivez devant une intersection', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (26, N'Boss', N'Vous entrez dans la salle du maitre, devant vous le mangemort que vous devez capturez', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (27, N'Mort Debile', N'Le mangemort vous tue avant que vous arriviez au corps à corps', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (28, N'Repli Strategique', N'Vous faites demi-tour et ressortez, vous entendez le mangemort se ruez sur vous', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (29, N'Inefficace', N'Votre sort est facilement contré', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (30, N'Pourparler', N'Le mangemort à l''air ouvert à la discussion.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (31, N'Efficace', N'Vous coupez la main du mangemort aussi tôt qu''il sort, il est à terre', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (32, N'Felicitations', N'Vous petrifiez le mangemort, votre mission est accompli. Bravo', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (33, N'Lisez les consignes', N'Vous avz tuez le mangemort... Votre mission était de le capturez.', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (34, N'Pas d''éloquence', N'Votre argument ne convint pas le mangemort qui vous tue sur le champ', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (35, N'So deep', N'Vos mots touche le mangemort en plein coeur il accepte de se rendre, vous avez accompli votre mission ?', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (37, N'Nice try', N'Vous pensiez pouvoir discutter après avoir tenté de capturez quelqu''un ? Seul la mort vous attend', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (38, N'Crache Limace', N'Dans la confusion vous lancez sur vous même le sort Crache Limace, dans votre malheur le mangemort à la phobie des limaces, et se retrouve à terre devant vous, cependant cela ne durera pas longtemps', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (39, N'Evanoui', N'Le mangemort s''evanoui devat vous. Vous avez réussi votre mission', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (40, N'Toothless', N'Un coup de pied bien placé lui fait perdre plusieurs de ces dents, dans l''incapacité de lancer le moindre sort vous le maitrisez facilement. Félicittions', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (41, N'Inutile', N'Le mangemort déverouille la porte grace à un sort d''allohomora', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (42, N'Muet', N'Le mangemort est muet pour un certain temps, cependant dans la panique vous n''arrivez pas à penser à un sort précis pour l''immobiliser', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (43, N'Attendre ?', N'Vous attendez, le mangemort ouvre la porte et vous tue. Vous vous attendiez à quoi ?', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (44, N'Grande Salle', N'Vous entrez dans une grande salle empli de table, vous reperrez dans un coin de la sall un portoloin', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (45, N'Grande Sall V2', N'Vous entrez dans une grande salle empli de table, vous reperrez dans un coin de la sall un portoloin', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (46, N'Inactif', N'Le Portoloin est malheuresement inactif.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (47, N'Toilettes', N'Vous vous retrouvez .... Dans des toilettes ??? Vous sentez une envie de faire caca monter en vous', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (48, N'Geôle', N'Vous arrivez dans les geôle du donjon dedans un garde qui, en vous voyant ,se lève prend, son épée en main et vous dit de partir sous peine de tater de mon épée', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (49, N'Plus fort que toi', N'Le sbire était en réalité un maitre de l''épée il vous tue sans grand problème.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (50, N'1v20', N'20 personnes arrive dans la pièce, il vous répère vous attaque et vous battent sans trop de difficulté', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (51, N'Révélation', N'Le sbire sous l''emprise de Imperium vous donne la positiondu mangemort : la porte de début du donjon, deux choix s''offre alors à vous, allez avértir le ministère pour obtenir des renforts ou combattre le mangermort seul.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (52, N'Renfort Raté', N'Le mangemort à très vite découvert vos manigances et à juste changer de repère', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (53, N'Repérage', N'Vous entrouvez la porte et appercevez une peronne dans la pièce sur laquelle donne les toilette, vous refermez discrétement la porte des toilettes.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (54, N'Quelqu''un arrive', N'Vous entendez une personne se rapprocher des toilletes.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (55, N'Porte dans ta gueule', N'En tentant de sortir vous prenez la porte en pleine tête, sonné le mangemort vous tue facilement', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (56, N'Surprise', N'Pris par surprise vous n''avez aucun mal à maitriser le mangemort', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (57, N'Orientation : 0/20', N'Perdu dans le donjon, vous tombez sur 3 sbires à la première intersection, emcombré par le corps du mangemort il vous térasse.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (58, N'Orientation : 20/20', N'Vous ouvrez la première porte sur votre chemin et par miracle sortez du donjon.', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (59, N'Pet Bruyant', N'Le bruit d''un de vos pet alerte une personne que vous entende arriver à toute vitesse', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (60, N'Baguette ?', N'Malheuresement ce n''est pas votre baguette que vous tenez entre vos main... Vous êtes mort (de honte et littéralement)', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (61, N'Face à face', N'Le mangemort se tiens face à vous et demande ce que vous faites la', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (62, N'Tout avouer', N'Bien evidemment il vous tue', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (63, N'Eloquance', N'Etonnement il vous croit, il ouvre la porte et vous indique la sortie, la première porte en partant à gauche, il fait demi-tour et vous montre donc son dos.', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (64, N'Prévisible', N'Le mangemort s''attendait à ce genre d''attaque surprise et vous bat sans trop de problème', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (65, N'20v1', N'Vous revenez avec tout un bataillon du ministère de la magie, le mangemort pris au dépourvu et maitrisé', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (66, N'Salle Artefacts 1', N'Vous trouvez dans les artefacts une baguette un anneau extrement rare que possède le mangemort, rammenez cette artefact ferait de cette mission une réussite', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (67, N'Potion cachée', N'Vous finissez par trouver une potion caché dans l''armoire ', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (68, N'Empoisonée', N'Elle était empoisonée dommage, vous mourrez lentement, agonisant au sol', 2)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (69, N'Salle Artefacts 2', N'Vous trouvez dans les artefacts une baguette un anneau extrement rare que possède le mangemort, rammenez cette artefact ferait de cette mission une réussite', 0)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (70, N'Bilan Mitigé', N'Vous fuyez le donjon avec la bague, le bilan est correct vous êtes en vie avec un artefact rare en votre possession, bien joué', 1)
INSERT INTO [dbo].[Scenario] ([Id], [Label], [Text], [GameOver]) VALUES (71, N'Fosse à serpents', N'Vous tombez dans la fosse à serpent du mangemort malheuresement vous ne parlez pas le fourchelangue, les serpents vous tue', 2)
SET IDENTITY_INSERT [dbo].[Scenario] OFF


SET IDENTITY_INSERT [dbo].[Choice] ON
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (1, 1, 2, N'Faire demi-tour, vous etes trop vieux pour ces conneries')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (2, 1, 3, N'Entrer dans le donjon')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (3, 3, 4, N'Sonner et entrer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (4, 3, 7, N'Continuer votre chemin')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (5, 4, 5, N'Avada Kedavra')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (6, 4, 6, N'Petrificus Totalus')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (7, 7, 8, N'Aller à gauche')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (8, 7, 9, N'Aller à droite')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (9, 7, 13, N'Faire demi-tour')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (10, 9, 8, N'Revenir sur ces pas et aller à gauche')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (11, 9, 10, N'Ouvrir la porte grace à un sort')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (12, 10, 11, N'Fuir')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (13, 10, 12, N'Combattre')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (14, 13, 4, N'Continuer vers la porte du départ et entrer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (15, 13, 19, N'Retourner à l''intersection')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (16, 13, 14, N'Prendre l''escalier')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (17, 10, 16, N'Patronus')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (18, 10, 15, N'Doloris')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (19, 10, 16, N'Expelliarmus')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (20, 10, 17, N'Au point et à la dague les sorts c''est pour les faibles')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (26, 14, 20, N'Utiliser votre dague')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (27, 14, 21, N'Utiliser votre baguette')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (28, 14, 22, N'Fuite')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (30, 15, 44, N'Continuer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (31, 15, 45, N'Se reposer un peu')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (34, 17, 18, N'Continuer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (35, 17, 45, N'Se reposer un peu')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (36, 20, 23, N'Fouiller la table')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (37, 20, 24, N'Fouiller l''armoire')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (38, 20, 25, N'Continuer plus loin')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (39, 21, 20, N'Sortir votre dague')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (40, 21, 22, N'Fuir')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (41, 23, 26, N'Salle du maître')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (42, 23, 66, N'Salle des artefacts')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (43, 24, 23, N'Fouiller la table')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (44, 24, 67, N'Continuer de fouiller l''armoire')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (45, 25, 71, N'Continuer tout droit')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (46, 25, 69, N'Tourner à gauche')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (47, 26, 27, N'Foncer tête baissée avec votre dague')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (48, 26, 28, N'Sortir')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (49, 26, 29, N'Petrificus Totalus')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (50, 26, 30, N'Parlementer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (51, 28, 21, N'Attendre avec votre dague sorti')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (52, 28, 41, N'Collaporta')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (53, 28, 42, N'Silencio')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (55, 28, 5, N'Avada kedavra')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (56, 29, 29, N'Petrificus Totalus')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (57, 29, 38, N'Lancer des sorts au hasard en chaine')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (58, 29, 37, N'Parlementer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (59, 30, 34, N'Je crois en vous')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (60, 30, 34, N'Vous êtes bon au fond de vous')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (61, 30, 34, N'Tu veux pas te laisser capturer ?')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (62, 30, 35, N'C''est pas gentil d''être méchant')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (63, 31, 33, N'Achever-le')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (64, 31, 32, N'Petrificus Totalus dans le doute')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (65, 38, 39, N'Lancer crache limace sur le mangemort')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (66, 38, 40, N'Coup de pied dans ces dents')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (67, 41, 41, N'Collaporta')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (68, 41, 43, N'Attendre')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (69, 41, 31, N'Dague')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (70, 42, 38, N'Lancer des sorts au hasard en chaine')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (71, 42, 33, N'Attaquer avec votre dague')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (72, 44, 46, N'Tenter d''activer le portoloin')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (73, 44, 48, N'Continuer plus loin dans le donjon')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (74, 45, 47, N'Tenter d''activer le portoloin')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (75, 45, 48, N'Continuer plus loin dans le donjon')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (76, 46, 50, N'Attendre que le portoloin soit activalbe')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (77, 46, 48, N'Continuer plus loin dans le donjon')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (78, 47, 53, N'Tenter de sortir discétement')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (79, 47, 59, N'Se poser sur le trone ')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (80, 48, 49, N'Attaquer avec votre dague')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (81, 48, 51, N'Utiliser Imperium ')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (82, 51, 26, N'Aller affronter le mangemort')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (83, 51, 52, N'Prévenir le ministère pour attaquer en nombre')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (84, 53, 54, N'Rester en embuscade')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (85, 53, 56, N'Sortir pour combattre l''ennemi')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (86, 54, 55, N'Sortir et attaquer')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (87, 54, 56, N'Attendre')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (88, 56, 57, N'Droite')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (89, 56, 58, N'Gauche')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (90, 59, 60, N'Sortir sa baguette')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (91, 59, 61, N'Se rhabiller')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (92, 61, 63, N'Je me suis perdu')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (93, 61, 62, N'Tout avouer ')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (94, 63, 64, N'Attaquer en traitre')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (95, 63, 65, N'Prévenir le ministère pour attaquer en nombre')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (96, 66, 26, N'Aller affronter le mangemort')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (97, 66, 70, N'Fuir du donjon')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (98, 67, 25, N'Continuer sa route')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (99, 67, 68, N'Boire la potion')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (100, 69, 71, N'Retourner à ''lintersection et prendre l''autre couloir')
INSERT INTO [dbo].[Choice] ([Id], [CurrentScenarioId], [NextScenarioId], [Text]) VALUES (101, 69, 70, N'Fuir')
SET IDENTITY_INSERT [dbo].[Choice] OFF
