//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isima.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoiceList()
        {
            this.Scenario = new HashSet<Scenario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Choice1Id { get; set; }
        public Nullable<int> Choice2Id { get; set; }
        public Nullable<int> Choice3Id { get; set; }
        public Nullable<int> Choice4Id { get; set; }
    
        public virtual Choice Choice { get; set; }
        public virtual Choice Choice1 { get; set; }
        public virtual Choice Choice2 { get; set; }
        public virtual Choice Choice3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario> Scenario { get; set; }
    }
}
