<<<<<<< HEAD

=======
>>>>>>> 18f1f07a708427d89c7bb54d590e9c2057e653aa
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD

namespace isima.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Map
{

    public int ID { get; set; }

    public string Configuration { get; set; }

}

=======
namespace isima.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int ID { get; set; }
        public string configuration { get; set; }
    }
>>>>>>> 18f1f07a708427d89c7bb54d590e9c2057e653aa
}
